### ISSUE TITLE
vagrant up not working on mac

### ISSUE THREAD

**Issue by tdcwilliams** [nansencenter/nersc-vagrant#16]
did "git pull"
and sudo port upgrade outdated

so code & ansible etc should be up-to-date

error:
==> course: Running provisioner: ansible...
    course: Running ansible-playbook...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i '/Users/timill/GITHUB-REPOSITORIES/python/nersc-vagrant/.vagrant/machines/course/virtualbox/private_key' -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --connection=ssh --timeout=30 --extra-vars=ansible_ssh_user='vagrant' --limit='course' --inventory-file=provisioning/hosts -v provisioning/site.yml
Traceback (most recent call last):
  File "/opt/local/bin/ansible-playbook", line 110, in <module>
    display.error("Unexpected Exception: %s" % to_unicode(e), wrap_text=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/utils/display.py", line 261, in error
    self.display(new_msg, color='red', stderr=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/utils/display.py", line 124, in display
    msg2 = to_bytes(msg2, encoding=self._output_encoding(stderr=stderr))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/utils/unicode.py", line 208, in to_bytes
    return obj.encode(encoding, errors)
LookupError: unknown encoding: 
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by mortenwh** [comment]
Why "port upgrade"? Should be enough with "vagrant provision course"..?
7. mai 2016 10.28 skrev "Timothy Williams" notifications@github.com:

**Comment by tdcwilliams** [comment]
to make sure ansible was updated (via macports) - it's not part of the
repo right?
"vagrant provision course"
gives the same error

**Comment by mortenwh** [comment]
Strange. You should check the git log of nersc-vagrant if any changes was
made lately that could affect the course vm. Do you know which version you
used before the pull? An option could be to just check out an earlier
version... or fix the error if you find it
7. mai 2016 10.44 skrev "Timothy Williams" notifications@github.com:

**Comment by tdcwilliams** [comment]
not sure what the old version was (quite old), but that had the same
error. Maybe it is an issue with ansible itself, but wouldn't know where
to start with fixing the error...

**Comment by tdcwilliams** [comment]
actually, from google, setting LC_ALL and LANG
to en_US.UTF-8

fixed it, and it seemed to work, except there were a lot of messages saying:

PLAY

---

skipping: no hosts matched

**Comment by akorosov** [comment]
These messages are OK. They tell you only run provisioning of the 'course' machine.

Where did you have to specify LC_ALL and LANG? In your machine or on the guest machine? I was trying to fix that issue here:
https://github.com/nansencenter/nersc-vagrant/commit/11f7235d873832b21fb89fa61c954dbacd99e990
But that affects only the guest machine, of course.

**Comment by tdcwilliams** [comment]
That was on my personal machine.
